version: 2.1
orbs:
  node: circleci/node@3.0.0
# Define the jobs we want to run for this project
jobs:
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  build:
    jobs:
      - build
